name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Log project structure for debugging
        run: |
          echo "Root directory:"
          ls -al
          echo "Contents of ./automated-testing directory:"
          ls -al ./automated-testing
        
      - name: Install Node Dependencies
        run: |
          cd ./automated-testing
          npm install
        shell: bash

      - name: Run npm Tests
        run: |
          cd ./automated-testing
          npm test
        shell: bash