name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Log project structure for debugging
        run: |
          echo "Root directory:"
          ls -al
          echo "Contents of ./automated-testing directory:"
          ls -al ./automated-testing

      - name: Install Node Dependencies
        working-directory: ./automated-testing
        run: npm install

      - name: Install Playwright Browsers
        working-directory: ./automated-testing
        run: npx playwright install --with-deps

      - name: Run npm Tests
        working-directory: ./automated-testing
        run: npm test
